#!/usr/bin/env bash

export SETUP_GROUPS=("hardware" "workstation")
export HOSTNAME=desktop-r7k
export PGP_PUBKEY_FILE="kenton_digaida_com_pub.asc"

# Uncomment any of the below lines to skip its step
export INC_SUDO=true
export INC_SOPS=true
export INC_GCLOUD=true
export INC_NITRO=true
export INC_SSH=true
export INC_GIT=true
export INC_CHROME=true
export INC_FLATPAK=true
export INC_FONTS=true
export INC_KVM=true
export INC_NITRO_PGP=true
export INC_NVIM=true
export INC_BITWARDEN=true
export INC_DISCORD=true
export INC_DISPLAYCAL=true
export INC_GHEX=true
export INC_MELD=true
export INC_REMMINA=true
export INC_SIGNAL=true
export INC_THUNDERBIRD=true
export INC_TRANSMISSION=true
export INC_NODE=true
export INC_PYTHON=true
export INC_RUST=true
export INC_ALACRITTY=true
export INC_DASHTODOCK=true
export INC_GNOME=true
export INC_ZFS=true
export INC_ZSH=true
