network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: false
      dhcp6: false
      addresses: [10.157.252.53/24]
      routes:
        - to-default:
            via: 10.157.252.254
